<?php

use Illuminate\Database\Seeder;

class ExternallinksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('externallinks')->insert([
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'1'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'1'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'1'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'1'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'1'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'1'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'1'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'2'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'2'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'2'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'2'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'2'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'2'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'2'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'3'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'3'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'3'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'3'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'3'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'3'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'3'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'4'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'4'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'4'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'4'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'4'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'4'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'4'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'5'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'5'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'5'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'5'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'5'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'5'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'5'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'6'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'6'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'6'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'6'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'6'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'6'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'6'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'7'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'7'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'7'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'7'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'7'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'7'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'7'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'8'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'8'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'8'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'8'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'8'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'8'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'8'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'9'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'9'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'9'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'9'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'9'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'9'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'9'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'10'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'10'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'10'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'10'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'10'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'10'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'10'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'11'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'11'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'11'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'11'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'11'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'11'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'11'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'12'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'12'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'12'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'12'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'12'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'12'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'12'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'13'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'13'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'13'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'13'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'13'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'13'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'13'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'14'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'14'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'14'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'14'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'14'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'14'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'14'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'15'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'15'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'15'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'15'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'15'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'15'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'15'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'16'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'16'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'16'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'16'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'16'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'16'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'16'
            ],
            [
                'link'=>'https://www.behance.net/kokooma',
                'id_user'=>'17'
            ],
            [
                'link'=>'https://dribbble.com/tamo_?fbclid=IwAR35Izl3jTgaQ6oYp0AIPFvnJ-839DBIpua0xwF_7bWzFFdhvuz2NFg8XJc',
                'id_user'=>'17'
            ],
            [
                'link'=>'https://www.facebook.com/thuan.tang.16',
                'id_user'=>'17'
            ],
            [
                'link'=>'https://www.youtube.com/channel/UCM0aQdLoLO83ftfruqQFSCw/videos',
                'id_user'=>'17'
            ],
            [
                'link'=>'https://wpbuilders.co/?fbclid=IwAR1LHOQHlkuOfa3PIcyeoW688L3RNY_nXXitiVBeXCh-KTPvk9rpIBHltd0',
                'id_user'=>'17'
            ],
            [
                'link'=>'https://www.pinterest.com/tranmautritam/?autologin=true&fbclid=IwAR0hWVyCkmGvOpjcwKyRwgfwhjtScEDjQMD7qKxUk9qJzba85OAkV69xR5U',
                'id_user'=>'17'
            ],
            [
                'link'=>'https://twitter.com/tranmautritam?fbclid=IwAR3hCgJeBD_f1vlkotXP7AMoShJjr2A1GhBjIYe3YfQGoPYnb0o4YyAcuKU',
                'id_user'=>'17'
            ],
        ]);
    }
}
